### ISSUE TITLE
Qwen2可以转onnx,转bmodel的时候出现以下问题

### ISSUE THREAD

**Issue by tzhang2014** [sophgo/LLM-TPU#30]
## 
sdk是v1.6.113-g7dc59c81-20240105, 转bmodel出现model_deploy.py: error: unrecognized arguments: --addr_mode io_alone
##
去掉--addr_mode 转bmodel报这个错误，我用的转模型命令是这个：./compile.sh --mode int8 --name qwen2-7b --seq_length 8192

Floating point exception (core dumped)
Traceback (most recent call last):
File "/workspace/tpu-mlir_v1.6.113-g7dc59c81-20240105/python/tools/model_deploy.py", line 337, in
tool.build_model()
File "/workspace/tpu-mlir_v1.6.113-g7dc59c81-20240105/python/tools/model_deploy.py", line 232, in build_model
mlir_to_model(self.tpu_mlir, self.model, self.final_mlir, self.dynamic,
File "/workspace/tpu-mlir_v1.6.113-g7dc59c81-20240105/python/utils/mlir_shell.py", line 169, in mlir_to_model
_os_system(cmd)
File "/workspace/tpu-mlir_v1.6.113-g7dc59c81-20240105/python/utils/mlir_shell.py", line 50, in _os_system
raise RuntimeError("[!Error]: {}".format(cmd_str))
RuntimeError: [!Error]: tpuc-opt block_cache_9_bm1684x_w8bf16_final.mlir --codegen="model_file=block_cache_9.bmodel embed_debug_info=false model_version=latest" -o /dev/nu

**Comment by tzhang2014** [comment]
去掉--addr_mode 转bmodel报这个错误，我用的转模型命令是这个：./compile.sh --mode int8 --name qwen2-7b --seq_length 8192

Floating point exception (core dumped)
Traceback (most recent call last):
  File "/workspace/tpu-mlir_v1.6.113-g7dc59c81-20240105/python/tools/model_deploy.py", line 337, in <module>
    tool.build_model()
  File "/workspace/tpu-mlir_v1.6.113-g7dc59c81-20240105/python/tools/model_deploy.py", line 232, in build_model
    mlir_to_model(self.tpu_mlir, self.model, self.final_mlir, self.dynamic,
  File "/workspace/tpu-mlir_v1.6.113-g7dc59c81-20240105/python/utils/mlir_shell.py", line 169, in mlir_to_model
    _os_system(cmd)
  File "/workspace/tpu-mlir_v1.6.113-g7dc59c81-20240105/python/utils/mlir_shell.py", line 50, in _os_system
    raise RuntimeError("[!Error]: {}".format(cmd_str))
RuntimeError: [!Error]: tpuc-opt block_cache_9_bm1684x_w8bf16_final.mlir --codegen="model_file=block_cache_9.bmodel embed_debug_info=false model_version=latest" -o /dev/nu

**Comment by chuxiaoyi2023** [comment]
版本太老噜，用这个https://github.com/sophgo/tpu-mlir
[d0cbae7](https://github.com/sophgo/tpu-mlir/commit/d0cbae79f499b3b2acde243dd94f5d2af86bb296)

不过这个要自己编译source envsetup.sh && ./build.sh DEBUG

**Comment by tzhang2014** [comment]
@chuxiaoyi2023 

可以转了哈，感谢
